# Generated by Django 4.2.11 on 2024-09-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
