# Generated by Django 4.2.2 on 2024-09-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('salespoint', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('link', models.URLField()),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
