# Generated by Django 4.2.9 on 2024-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_book_category_id_alter_book_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fixed_price',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
